name:                huarong-haskell
version:             0.1.0.0
github:              "madun1999/huarong-haskell"
license:             BSD3
author:              "Dun Ma, Jiewen Yang, Mohan Li, Jinyi Mu"
maintainer:          "madun1999@gmail.com"
copyright:           "2021 Dun Ma, Jiewen Yang, Mohan Li, Jinyi Mu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/madun1999/huarong-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- text
- vty
- microlens-th
- microlens
- lens
- bytestring
- network-bsd
- network
- aeson
- uuid
- mtl
- QuickCheck

library:
  source-dirs: src

executables:
  huarong-haskell-exe:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - huarong-haskell

  huarong-haskell-server-exe:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - huarong-haskell
    

tests:
  huarong-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - huarong-haskell